  name: build-github-actions
  on: [push]
  jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
          with:
            node-version: '16'
        - run: node -v
        - run: npm -v
        - run: npm i -G yarn
        - run: yarn
